controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index # TODO : ce que renvoie la classe

detail:
    path: /detail
    controller: App\Controller\DetailController::showArticles # TODO : ce que renvoie la classe

cart:
    path: /cart
    controller: App\Controller\CartController::index # TODO : ce que renvoie la classe

validate:
    path: /cart/validate
    controller: App\Controller\ValidateController::index # TODO : ce que renvoie la classe

edit:
    path: /edit
    controller: App\Controller\EditController::index # TODO : ce que renvoie la classe

#account:
#    path: /account
#    controller: App\Controller\AccountController::account # TODO : ce que renvoie la classe

admin:
    path: /admin
    controller: App\Controller\AdminController::index # TODO : ce que renvoie la classe



article_image:
    path: /article/{id}/image
    controller: App\Controller\PictureController::getPicture

