controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

detail:
    path: /detail
    controller: App\Controller\DetailController::showArticles

cart:
    path: /cart
    controller: App\Controller\CartController::index

validate:
    path: /cart/validate
    controller: App\Controller\ValidateController::index

edit:
    path: /edit/{id}
    controller: App\Controller\EditController::editArticle

account:
    path: /account
    controller: App\Controller\AccountController::account

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

article_image:
    path: /article/{id}/image
    controller: App\Controller\PictureController::getPicture

profil_picture:
    path: /user/{id}/image
    controller: App\Controller\PictureController::getProfilePicture

article_detail:
    path: /article/{id}
    controller: App\Controller\DetailController::show